title: Systemantic Open Source Projects
logo: https://res.cloudinary.com/systemantic/image/upload/v1530192863/systemantic/systemantic%20logo/Jpeg%20Version/Systemantic_Logo_White.jpg
description: At Systemantic we are solving problems and sharing the knowledge with our community. Here we present many projects as boilerplates that would help developers avoiding the headache of configuration and setting environments. Our boilerplates contain the latest Web technologies and dev tools.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal